chore(fetch-wrapper): improve error message when 'fetch' implementation is not present
octokit/request.js pull request #617
Opened 2023-07-15 01:31 UTC by oscard0m

Resolves #ISSUE_NUMBER

----

## Behavior

### Before the change?

*

### After the change?

*

### Other information

*

----

## Additional info

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [ ] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

2023-07-15 01:56 UTC, wolfy1339 approved these changes

2023-07-18 01:08 UTC, gr2m requested changes
I changed to commit message to a fix, as it's changing behavior in production.

I block the pull request just in case as we should merge https://github.com/octokit/octokit.js/pull/2502 first

2023-07-18 14:29 UTC, nickfloyd commented
https://github.com/octokit/octokit.js/pull/2502 should be g2g in my opinion.

2023-07-18 14:29 UTC, nickfloyd approved these changes

2023-07-19 00:28 UTC, gr2m approved these changes

2023-07-19 00:28 UTC, merged